name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'Upload artifact to this run? [yes | no]'
        required: false
        default: 'no'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_buildNumber: ${{ github.run_number }}
      ORG_GRADLE_PROJECT_runAttempt: ${{ github.run_attempt }}
      ORG_GRADLE_PROJECT_runningOnCi: ${{ true }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    - name: Read Project Version
      id: read_project_version
      if: ${{ github.ref_name == 'main' || contains(github.event.inputs.upload_artifact, 'yes') }}
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: gradle.properties
        properties: version
    - name: Upload Artifact
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || contains(github.event.inputs.upload_artifact, 'yes') }}
      uses: actions/upload-artifact@v3
      with:
        name: Fancy Warp Menu
        path: build/libs/*
    - name: Get Head Commit Message
      id: get_head_commit_message
      run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=format:"%B")" >> "$GITHUB_OUTPUT"
    - name: Post Build Information to Discord
      if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch' && contains(github.event.inputs.upload_artifact, 'yes') }}
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.BUILD_WEBHOOK_URL }}
        embed-title: ${{ steps.read_project_version.outputs.version }} Build \#${{ github.run_number }}
        embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/
        embed-description: ${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}
        filename: build/libs/FancyWarpMenu-${{ steps.read_project_version.outputs.version }}.${{ github.run_number }}.jar
