name: Upload Sources to Crowdin

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/resources/lang/en_US.lang'
jobs:
  upload:
    name: Upload Sources to Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: crowdin/github-action@v1
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}